import { Task } from '@core/types/task';

export const TASKS: Task[] = [
  {
    id: 1,
    name: 'Task Editor',
    description: `### Build task editor\n - Task name input - Description textarea`,
    files: [],
    priority: 'normal',
    type: 'feature',
    status: 'todo',
  },
  {
    id: 2,
    name: 'Profile Page',
    description: 'Fix bug on Profile Page with render',
    files: [],
    priority: 'high',
    type: 'bug',
    status: 'todo',
  },
  {
    id: 3,
    name: 'Add search',
    description: 'Add search to Header component',
    files: [],
    priority: 'low',
    type: 'feature',
    status: 'done',
  },
  {
    id: 4,
    name: 'Update logo',
    description: 'Update logo in sidebar',
    files: [],
    priority: 'normal',
    type: 'improvement',
    status: 'in progress',
  },
  {
    id: 5,
    name: 'Fix Sidebar',
    description: 'Fix links in sidebar',
    files: [],
    priority: 'high',
    type: 'bug',
    status: 'todo',
  },
  {
    id: 6,
    name: 'Implement Stubs for loading',
    description: 'Add stubs for loading on all pages',
    files: [],
    priority: 'low',
    type: 'feature',
    status: 'in review',
  },
  {
    id: 7,
    name: 'Task Card component',
    description: 'Add Task Card component',
    files: [],
    priority: 'normal',
    type: 'feature',
    status: 'todo',
  },
  {
    id: 8,
    name: 'Dragn&Drop',
    description: 'Add drag&drop for tasks card on /board',
    files: [],
    priority: 'low',
    type: 'feature',
    status: 'todo',
  },
  {
    id: 9,
    name: 'Add email and fullname',
    description: 'Add email and fullname to profile dropdown',
    files: [],
    priority: 'normal',
    type: 'improvement',
    status: 'todo',
  },
  {
    id: 10,
    name: 'Add email and fullname',
    description: 'Add email and fullname to profile dropdown',
    files: [],
    priority: 'normal',
    type: 'improvement',
    status: 'todo',
  },
  {
    id: 11,
    name: 'Add Board page',
    description: 'Create Board page with route /board',
    files: [],
    priority: 'normal',
    type: 'feature',
    status: 'todo',
  },
  {
    id: 13,
    name: 'Fix logout',
    description: 'Throws an error when clicking logout in dropdown component',
    files: [],
    priority: 'high',
    type: 'bug',
    status: 'todo',
  },
  {
    id: 14,
    name: 'Move preloader to top',
    description: '-',
    files: [],
    priority: 'normal',
    type: 'improvement',
    status: 'todo',
  },
  {
    id: 15,
    name: 'Add custom scroll',
    description: 'Add wrapper component for enabling custom scroll',
    files: [],
    priority: 'normal',
    type: 'feature',
    status: 'todo',
  },
  {
    id: 16,
    name: 'Add media queries',
    description: 'Add wrapper component for enabling custom scroll',
    files: [],
    priority: 'low',
    type: 'feature',
    status: 'todo',
  },
];
